name: watchtower

services:
  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    restart: always
    environment:
      - TZ=Asia/Seoul
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_NOTIFICATION_URL=/run/secrets/watchtower_notification_url
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - watchtower_notification_url
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

secrets:
  watchtower_notification_url:
    file: ${SECRETS_DIR:-${HOME}/.secrets}/watchtower_notification_url
