name: matterjs-server

services:
  matterjs-server:
    container_name: matterjs-server
    image: ghcr.io/matter-js/matterjs-server:stable
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${DOCKER_DATA_PATH:-${HOME}/docker-data}/matterjs-server:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      PORT: '5580'
      LISTEN_ADDRESS: 127.0.0.1
      TZ: Asia/Seoul
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
